In [1]:
pip install zstandard

Collecting zstandardNote: you may need to restart the kernel to use updated packages.

  Downloading zstandard-0.23.0-cp38-cp38-win_amd64.whl (495 kB)
Installing collected packages: zstandard
Successfully installed zstandard-0.23.0

In [3]:
pip install zstandard requests

Requirement already satisfied: zstandard in f:\softwareinstallationfiles\lib\site-packages (0.23.0)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: requests in f:\softwareinstallationfiles\lib\site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in f:\softwareinstallationfiles\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\softwareinstallationfiles\lib\site-packages (from requests) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in f:\softwareinstallationfiles\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in f:\softwareinstallationfiles\lib\site-packages (from requests) (2.10)

# 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [ ]:
import io
import requests
import pandas as pd
import zstandard as zstd

base_url = "https://raw.githubusercontent.com/Shah-1510/Trending-YouTube-Dataset-FCS-2025-26-Project"

files = [
    "CAvideos.csv.zst", "DEvideos.csv.zst", "FRvideos.csv.zst", "GBvideos.csv.zst",
    "INvideos.csv.zst", "JPvideos.csv.zst", "KRvideos.csv.zst", "MXvideos.csv.zst",
    "RUvideos.csv.zst", "USvideos.csv.zst"
]

dfs = []
for file in files:
    country = file[:2]
    url = base_url + file
    print("Downloading:", url)
    resp = requests.get(url)
    resp.raise_for_status()

    dctx = zstd.ZstdDecompressor()
    # fully decompress into bytes
    with dctx.stream_reader(io.BytesIO(resp.content)) as reader:
        decompressed_bytes = reader.read()  # returns bytes

    # decode safely. errors='replace' will replace invalid sequences with ?
    # If you prefer to preserve bytes without decode errors, use latin1 instead:
    # text = decompressed_bytes.decode('latin1')
    text = decompressed_bytes.decode('utf-8', errors='replace')

    # read into pandas from a text buffer
    df = pd.read_csv(io.StringIO(text))
    df["country"] = country
    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)
print("Combined rows:", len(final_df))
final_df.to_csv("final_df.csv", index=False)

In [3]:
final_df.head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

In [4]:
# Changing the Date Format into Proper (yyyy-dd-mm)

In [5]:
final_df['trending_date'] = pd.to_datetime(final_df['trending_date'], format='%y.%d.%m')

In [6]:
final_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

# 2. Extract all videos that have no tag.

In [7]:
no_tag_videos = final_df[
    (final_df['tags'] == '[none]') |
    (final_df['tags'].isna()) |
    (final_df['tags'].str.strip() == '')
]

no_tag_videos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,2017-11-14,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,2017-11-14,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,2017-11-14,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,2017-11-14,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,2017-11-14,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA

In [8]:
print("There are",no_tag_videos.shape[0],"Videos which have no Tag")

There are 37698 Videos which have no Tag

# 3. For each channel, determine the total number of views

In [9]:
print("The Channels with Total Number of Views Sorted in Highest to Lowest are as follows: ")
channel_views = final_df.groupby('channel_title')['views'].sum().reset_index()
channel_views = channel_views.sort_values(by='views', ascending=False)
channel_views

The Channels with Total Number of Views Sorted in Highest to Lowest are as follows:

              channel_title        views
4564    ChildishGambinoVEVO  11016766510
15536  Marvel Entertainment  10430605449
17726            NickyJamTV   9479859505
18466                 Ozuna   8623329509
28412               ibighit   8205572221
...                     ...          ...
17437     NavylittleMonster          365
25828      Videostendencias          302
17837         No Comment TV          284
22560            Sport Life          163
1370      Alexander Redking          153

[37824 rows x 2 columns]

# 4.  Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [10]:
# Create the excluded dataframe
excluded = final_df[
    (final_df['comments_disabled'] == True) |
    (final_df['ratings_disabled'] == True) |
    (final_df['video_error_or_removed'] == True)
]

# Remove those rows from the original dataframe
final_df = final_df.drop(excluded.index).reset_index(drop=True)

# Display how many rows were excluded
print(f"Total excluded rows from the Original Dataframe: {excluded.shape[0]}")
print(f"Remaining rows in the Original Dataframe: {final_df.shape[0]}")

Total excluded rows from the Original Dataframe: 13657
Remaining rows in the Original Dataframe: 362285

# 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [11]:
final_df['like_ratio'] = final_df.apply(
    lambda row: round(row['likes'] / row['dislikes'], 3) if row['dislikes'] > 0 else None,
    axis=1
)

In [12]:
final_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.353
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513

# 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [13]:
final_df['publish_time'] = pd.to_datetime(final_df['publish_time'])

def interval_label(dt):
    start = dt.floor('10T')
    end = start + pd.Timedelta(minutes=10)
    return f"{start.strftime('%H:%M')} – {end.strftime('%H:%M')}"

final_df['publish_time_interval'] = final_df['publish_time'].apply(interval_label)

In [14]:
final_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_time_interval
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135,17:00 – 17:10
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707,17:00 – 17:10
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.353,19:00 – 19:10
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485,18:00 – 18:10
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513,11:00 – 11:10

# 7. For each interval, determine the number of videos, average number of likes and of dislikes

In [15]:
interval_stats = final_df.groupby('publish_time_interval').agg(
    No_of_Videos = ('video_id', 'count'),
    Avg_No_of_likes = ('likes', 'mean'),
    Avg_No_of_dislikes = ('dislikes', 'mean')
).reset_index()

In [16]:
interval_stats['Avg_No_of_likes'] = interval_stats['Avg_No_of_likes'].round(3)
interval_stats['Avg_No_of_dislikes'] = interval_stats['Avg_No_of_dislikes'].round(3)

In [17]:
interval_stats

    publish_time_interval  No_of_Videos  Avg_No_of_likes  Avg_No_of_dislikes
0           00:00 – 00:10          2826        62819.250            3902.800
1           00:10 – 00:20          1424        20898.900            1448.770
2           00:20 – 00:30          1199        22120.715            1109.575
3           00:30 – 00:40          1557        38038.324             981.209
4           00:40 – 00:50          1217        43956.825            1988.883
..                    ...           ...              ...                 ...
139         23:10 – 23:20          1512        23230.928            1135.510
140         23:20 – 23:30          1391        31700.416            1209.288
141         23:30 – 23:40          1613        18693.860             895.173
142         23:40 – 23:50          1414        47406.603            9683.547
143         23:50 – 00:00          1216        11003.608             522.613

[144 rows x 4 columns]

# 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags.

In [18]:
final_df['tag_list'] = final_df['tags'].str.split('|')

In [20]:
# Split the 'tags' column by '|' into multiple columns
tags_split = final_df['tags'].str.split('|', expand=True)

# Optional: rename columns as tag_1, tag_2, ...
tags_split.columns = [f'tag_{i+1}' for i in range(tags_split.shape[1])]

# Concatenate with the original dataframe if you want
final_with_tags = pd.concat([final_df, tags_split], axis=1)

# Show first 10 rows
final_with_tags[['video_id', 'tags'] + list(tags_split.columns)].head(10)

,video_id,tags,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8,...,tag_143,tag_144,tag_145,tag_146,tag_147,tag_148,tag_149,tag_150,tag_151,tag_152
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Eminem,"""Walk""","""On""","""Water""","""Aftermath/Shady/Interscope""","""Rap""",None,None,...,None,None,None,None,None,None,None,None,None,None
1,0dBIkQ4Mz1M,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",plush,"""bad unboxing""","""unboxing""","""fan mail""","""idubbbztv""","""idubbbztv2""","""things""","""best""",...,None,None,None,None,None,None,None,None,None,None
2,5qpjK5DgCt4,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",racist superman,"""rudy""","""mancuso""","""king""","""bach""","""racist""","""superman""","""love""",...,None,None,None,None,None,None,None,None,None,None
3,d380meD0W0M,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",ryan,"""higa""","""higatv""","""nigahiga""","""i dare you""","""idy""","""rhpc""","""dares""",...,None,None,None,None,None,None,None,None,None,None
4,2Vv-BfVoq4g,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",edsheeran,"""ed sheeran""","""acoustic""","""live""","""cover""","""official""","""remix""","""official video""",...,None,None,None,None,None,None,None,None,None,None
5,0yIWz1XEeyc,"#DramaAlert|""Drama""|""Alert""|""DramaAlert""|""keem...",#DramaAlert,"""Drama""","""Alert""","""DramaAlert""","""keemstar""","""youtube news""","""jake paul""","""team 10""",...,None,None,None,None,None,None,None,None,None,None
6,_uM5kFfkhB8,"Funny Moments|""Montage video games""|""gaming""|""...",Funny Moments,"""Montage video games""","""gaming""","""Vanoss""","""VanossGaming""","""Gameplay""","""Secret""","""Puncake""",...,None,None,None,None,None,None,None,None,None,None
7,2kyS6SvSYSE,SHANtell martin,SHANtell martin,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,JzCsM1vtn78,"logan paul vlog|""logan paul""|""logan""|""paul""|""o...",logan paul vlog,"""logan paul""","""logan""","""paul""","""olympics""","""logan paul youtube""","""vlog""","""daily""",...,None,None,None,None,None,None,None,None,None,None
9,43sm-QwLcx4,"God|""Sheldon Cooper""|""Young Sheldon""",God,"""Sheldon Cooper""","""Young Sheldon""",None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [19]:
final_df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_time_interval,tag_list
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135,17:00 – 17:10,"[Eminem, ""Walk"", ""On"", ""Water"", ""Aftermath/Sha..."
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707,17:00 – 17:10,"[plush, ""bad unboxing"", ""unboxing"", ""fan mail""..."
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.353,19:00 – 19:10,"[racist superman, ""rudy"", ""mancuso"", ""king"", ""..."
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485,18:00 – 18:10,"[ryan, ""higa"", ""higatv"", ""nigahiga"", ""i dare y..."
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513,11:00 – 11:10,"[edsheeran, ""ed sheeran"", ""acoustic"", ""live"", ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362280,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552,13:00 – 13:10,"[aarons animals, ""aarons"", ""animals"", ""cat"", ""..."
362281,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US,157.089,01:00 – 01:10,[[none]]
362282,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.578,17:30 – 17:40,[I gave safiya nygaard a perfect hair makeover...
362283,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799,17:00 – 17:10,"[Black Panther, ""HISHE"", ""Marvel"", ""Infinity W..."
362284,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.677,17:00 – 17:10,"[call of duty, ""cod"", ""activision"", ""Black Ops..."

In [43]:
tag_exploded = final_df.explode('tag_list')

In [44]:
tag_exploded['tag_list'] = tag_exploded['tag_list'].str.strip()           # remove spaces
tag_exploded['tag_list'] = tag_exploded['tag_list'].str.replace('"', '')  # remove quotes

In [45]:
tag_counts = tag_exploded['tag_list'].value_counts().reset_index()
tag_counts.columns = ['tag', 'video_count']

In [46]:
tag_counts

                                 tag  video_count
0                             [none]        35518
1                              funny        14940
2                             comedy        12289
3                               2018        10915
4                               news         5986
...                              ...          ...
831130          전자 레인지 쿠키 초콜릿 쿠키 디저트            1
831131                     Akhbar 2m            1
831132  les femmes sont plus fidèles            1
831133             выгоняют на улицу            1
831134             Майнинг НЕВЫГОДЕН            1

[831135 rows x 2 columns]

In [47]:
tag_counts = tag_counts[~tag_counts['tag'].str.lower().isin(['[none]', 'none', 'nan', ''])]

In [48]:
tag_counts

                                 tag  video_count
1                              funny        14940
2                             comedy        12289
3                               2018        10915
4                               news         5986
5                              music         5862
...                              ...          ...
831130          전자 레인지 쿠키 초콜릿 쿠키 디저트            1
831131                     Akhbar 2m            1
831132  les femmes sont plus fidèles            1
831133             выгоняют на улицу            1
831134             Майнинг НЕВЫГОДЕН            1

[831131 rows x 2 columns]

# 9. Find the tags with the largest number of videos

In [49]:
# Sort by video_count descending
top_tags = tag_counts.sort_values(by='video_count', ascending=False)

# Display top 10 tags
top_tags.head(10)

           tag  video_count
1        funny        14940
2       comedy        12289
3         2018        10915
4         news         5986
5        music         5862
6        video         5558
7         2017         5521
8        humor         5013
9   television         4109
10      review         4046

# 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [51]:
# Step 1: Ensure like_ratio exists
tag_exploded['like_ratio'] = tag_exploded.apply(
    lambda row: row['likes'] / row['dislikes'] if row['dislikes'] > 0 else None,
    axis=1
)

# Step 2: Group by tag and country, compute average
tag_country_stats = tag_exploded.groupby(['tag_list', 'country'])['like_ratio'].mean().reset_index()

# Step 3: Round to 3 decimals
tag_country_stats['like_ratio'] = tag_country_stats['like_ratio'].round(3)

# Step 4: (Optional) sort by highest like_ratio
tag_country_stats = tag_country_stats.sort_values(by='like_ratio', ascending=False)

# Display top 10 tag-country pairs
tag_country_stats.head(10)

                     tag_list country  like_ratio
88211               Direct TV      RU     11688.0
28385   AT&T AUDIENCE Network      RU     11688.0
281453                U-Verse      RU     11688.0
206058              Originals      RU     11688.0
28382                    AT&T      RU     11688.0
88213                DirectTV      RU     11688.0
28384           AT&T AUDIENCE      RU     11688.0
28562        AUDIENCE Network      RU     11688.0
28386          AT&T Originals      RU     11688.0
28511                     ATT      RU     11688.0

In [53]:
tag_country_stats['like_ratio'] = tag_country_stats['like_ratio'].fillna(0)
tag_country_stats

                      tag_list country  like_ratio
88211                Direct TV      RU     11688.0
28385    AT&T AUDIENCE Network      RU     11688.0
281453                 U-Verse      RU     11688.0
206058               Originals      RU     11688.0
28382                     AT&T      RU     11688.0
...                        ...     ...         ...
1073969       해적 루피 vs 장성 카타쿠리      KR         0.0
1074055                   핵 웃긴      KR         0.0
1074427                 헤이세이점프      KR         0.0
1074561                   현실술판      KR         0.0
1076059             ＧＡＮＧＰＡＲＡＤＥ      JP         0.0

[1076235 rows x 3 columns]

# 11. For each (trending_date, country) pair, the video with the largest number of views

In [56]:
# For each trending_date and country, get the index of the video with max views
idx = final_df.groupby(['trending_date', 'country'])['views'].idxmax()

# Use these indices to select the rows
most_viewed_videos = final_df.loc[idx].reset_index(drop=True)
most_viewed_videos[['trending_date', 'country', 'video_id', 'title', 'views']].head(10)

,trending_date,country,video_id,title,views
0,2017-11-14,CA,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622
1,2017-11-14,DE,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622
2,2017-11-14,FR,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622
3,2017-11-14,GB,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622
4,2017-11-14,IN,ePO5M5DE01I,Tiger Zinda Hai | Official Trailer | Salman Kh...,35885754
5,2017-11-14,KR,n1WpP7iowLc,Eminem - Walk On Water (Audio) ft. Beyoncé,17158579
6,2017-11-14,MX,JzCsM1vtn78,THE LOGANG MADE HISTORY. LOL. AGAIN.,4477587
7,2017-11-14,RU,U_4BLnJuR3g,12 лайфхаков с термоклеем для хендмейда,2109573
8,2017-11-14,US,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),33523622
9,2017-11-15,CA,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),39082222

# 12. Divide trending_date into three columns: year, month, day

In [58]:
# Extract year, month, day
final_df['year'] = final_df['trending_date'].dt.year
final_df['month'] = final_df['trending_date'].dt.month
final_df['day'] = final_df['trending_date'].dt.day
final_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,video_error_or_removed,description,country,like_ratio,publish_interval_label,publish_time_interval,tag_list,year,month,day
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135,17:00 – 17:10,17:00 – 17:10,"[Eminem, ""Walk"", ""On"", ""Water"", ""Aftermath/Sha...",2017,11,14
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,STill got a lot of packages. Probably will las...,CA,75.707,17:00 – 17:10,17:00 – 17:10,"[plush, ""bad unboxing"", ""unboxing"", ""fan mail""...",2017,11,14
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.353,19:00 – 19:10,19:00 – 19:10,"[racist superman, ""rudy"", ""mancuso"", ""king"", ""...",2017,11,14
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,False,I know it's been a while since we did this sho...,CA,66.485,18:00 – 18:10,18:00 – 18:10,"[ryan, ""higa"", ""higatv"", ""nigahiga"", ""i dare y...",2017,11,14
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513,11:00 – 11:10,11:00 – 11:10,"[edsheeran, ""ed sheeran"", ""acoustic"", ""live"", ...",2017,11,14

# 13: For each (month, country) pair, the video with the largest number of views

In [59]:
# Get index of video with max views for each (month, country) pair
idx = final_df.groupby(['month', 'country'])['views'].idxmax()

# Select those rows
most_viewed_month_country = final_df.loc[idx].reset_index(drop=True)
most_viewed_month_country[['month', 'country', 'video_id', 'title', 'views']].head(10)

,month,country,video_id,title,views
0,1,CA,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,43067983
1,1,DE,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,37728802
2,1,FR,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,37728802
3,1,GB,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,90598955
4,1,IN,dfnCAmr569k,"Taylor Swift - End Game ft. Ed Sheeran, Future",42019590
5,1,KR,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,37728802
6,1,MX,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,31680160
7,1,RU,dfnCAmr569k,"Taylor Swift - End Game ft. Ed Sheeran, Future",23198594
8,1,US,LsoLEjrDogU,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,57951412
9,2,CA,xpVfcZ0ZcFM,Drake - God’s Plan,47362934

# 14. Read all json files with the video categories

In [63]:
import pandas as pd
import json
import os

# Load JSON category files from local data/ folder
json_files = [
    "CA_category_id.json",
    "DE_category_id.json",
    "FR_category_id.json",
    "GB_category_id.json",
    "IN_category_id.json",
    "JP_category_id.json",
    "KR_category_id.json",
    "MX_category_id.json",
    "RU_category_id.json",
    "US_category_id.json"
]

all_categories = []

for file in json_files:
    country = file[:2]  # extract country code
    filepath = os.path.join("data", file)
    
    # Read JSON from local file
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Normalize items into dataframe
    df = pd.json_normalize(data["items"])
    
    # Add country column
    df["country"] = country
    
    all_categories.append(df)

# Combine all JSON files into one dataframe
categories_df = pd.concat(all_categories, ignore_index=True)

categories_df

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,US
307,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,US
308,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,US
309,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,US
310,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,US

# 15. For each country, determine how many videos have a category that is not assignable.

In [64]:
# Filter categories that are not assignable
non_assignable = categories_df[categories_df['snippet.assignable'] == False]

# Count number of categories per country
non_assignable_count = non_assignable.groupby('country').size().reset_index(name='non_assignable_count')

non_assignable_count

  country  non_assignable_count
0      CA                    17
1      DE                    17
2      FR                    17
3      GB                    17
4      IN                    17
5      JP                    17
6      KR                    17
7      MX                    17
8      RU                    17
9      US                    17